services:
  obsidian:
    image: linuxserver/obsidian:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    ports:
      - 3000:3000
    volumes:
      - config:/config
      - vaults:/vaults

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cf-tunnel
    command: tunnel run --url http://obsidian:3000 --token ${CLOUDFLARE_TOKEN}
    depends_on:
      - obsidian
    restart: always

volumes:
  config:
  vaults:
